### ISSUE TITLE
Being maintained or not?

### ISSUE THREAD

**Issue by agauniyal** [nirm03/SublimeLinter-clang#13]
Last commit is on Jan 7 , 2014 and new issues and PR are already pending on this repository. Is there any other fork or similar project that is being maintained?

**Comment by kumarashutosh** [comment]
Looking forward to this ...

**Comment by nirm03** [comment]
Hi guys,
sorry for neglecting this for the past year.
I promise to go over all the pull requests this week and merging them in as soon as possible.
I'll close this once they are all reviewed and pulled.

**Comment by agauniyal** [comment]
@nirm03 Thanks a lot :smile:

**Comment by GhostLyrics** [comment]
@nirm03: I don't want to be annoying but it's okay if you say you don't have the time to do it. It seems like there are a hand full of users who would be willing to do it for you. :)

Or you might consider adding a collaborator.

**Comment by kumarashutosh** [comment]
Ah Thanks :smile:

**Comment by dralley** [comment]
Hey @nirm03, I know you said you'd try to look over it, but if you're too busy to give proper attention to the pull requests I wouldn't mind helping out

**Comment by dralley** [comment]
@nirm03, any plans to merge the pull requests...?

**Comment by agauniyal** [comment]
@nirm03 , it is okay if don't have enough time for contribution to this project. The reason why me and other handful of developers are trying to contact you is because this is an absolutely good plugin in sublime text repository. You can add a collaborator or just ask one of developers to fork and maintain this project if you want to :)

**Comment by z3t0** [comment]
@agauniyal Totally agreed. This is an amazing plugin we would not want any of your efforts to go to waste. Please add some more people to the contributors list.

**Comment by GhostLyrics** [comment]
Since @nirm03's last comment is from March, I'd suggest waiting a bit more, say, June 1st 2015 and if nothing happens by then someone from the volunteers forks the repository.

I am aware that this is quite harsh, but any changes can always be merged back into this if/when they decide that development on the original fork should be resumed. _Unfortunately I don't know how one would get the forked version into Package Control, though._

**Comment by z3t0** [comment]
Agreed. Well as far as I can see this is no longer in Package Control (ST3)

**Comment by dralley** [comment]
The plugin is still listed in Package Control under the name [SublimeLinter-contrib-clang](https://packagecontrol.io/packages/SublimeLinter-contrib-clang).  The "contrib" bit is due to SublimeLinter's [policy](http://sublimelinter.readthedocs.org/en/latest/creating_a_linter.html) of using that infix to differentiate "unofficial" plugins from the ones they created and maintain themselves.

@GhostLyrics I agree.  It looks like someone actually [forked it already](https://github.com/kernhanda/SublimeLinter-clang), but I haven't really looked into how good their additions are and I'm not sure whether they're willing to maintain an official fork that people are downloading from.

**Comment by z3t0** [comment]
@dralley ok that makes sense

**Comment by agauniyal** [comment]
@GhostLyrics agreed. And in any case if author does comes back in future to maintain actively , we could provide an up to date PR to him. Lets wait till 1st June , then anyone who's capable of actively maintaining another fork of this repo could do that. 
@dralley we could (for the time being) name that fork as sublime-linter-clang-fork. Name would not matter till we're getting required functionality.

**Comment by dralley** [comment]
@agauniyal Do you mean getting a separate plugin added to Package Control, or changing the Package Control manifest to track a maintained fork instead of @nirm03 s?

**Comment by nirm03** [comment]
Sorry guys. Just took a look at my email for the first time since a while ago and saw these (rightfully) frustrated threads.

Due to medical issues and a child birth  I was unable to attend to this, but I'm currently testing these changes and will be sure to commit everything ASAP.

I'll also happily add a contributor so this neglect does not recur.

Whoever's interested, just say I...

—

**Comment by dralley** [comment]
Hey @nirm03, I'm glad you're alright!  I'd be happy to help with maintenance.

And congrats on the kid :)

**Comment by z3t0** [comment]
Hi @nirm03 congratulations on the child and I hope all becomes well. 
Count me in as a solid contributor! Happy to help!

**Comment by agauniyal** [comment]
@nirm03 congratulations :) and I hope you're doing well. 

Some PR's already solve what other PR's are trying to achieve. I would advise to read all PR's and merge them priority wise and then others would rebase those changes back into their personal PR's.

**Comment by nirm03** [comment]
Thanks guys, @dralley, I just added you as a collaborator, and also pushed the pending PRs, after a bit of reviewing and a bit of editing. Let me know if there is anything I'm still overlooking.
Feel free to close this issue once you're satisified with the current maintenance.

Thanks.

**Comment by dralley** [comment]
Thanks :)

I think we can also merge PR #12 for [C++11 syntax](https://packagecontrol.io/packages/C%2B%2B11) support unless you have an objection.

**Comment by nirm03** [comment]
Sure.

**Comment by dralley** [comment]
@nirm03 I no longer have interest in being the maintainer for this, perhaps @Optiligence would like to do so?

**Comment by Optiligence** [comment]
😄 I don’t use it as often, but I’d have no problem doing it.
